import type { StateCarrierRow } from "@/lib/data";

export const MAINE_CARRIERS: StateCarrierRow[] = [
  {
    name: "Pine State Freight Co.",
    city: "Portland",
    dot: "7412083",
    equipment: "Reefer",
    trucks: 6,
    status: "ACTIVE",
    score: 88,
  },
  {
    name: "Katahdin Logistics",
    city: "Bangor",
    dot: "7423916",
    equipment: "Flatbed",
    trucks: 4,
    status: "ACTIVE",
    score: 82,
  },
  {
    name: "Casco Bay Transport",
    city: "South Portland",
    dot: "7431750",
    equipment: "Dry van",
    trucks: 9,
    status: "ACTIVE",
    score: 91,
  },
  {
    name: "Volga Line Transport",
    city: "Lewiston",
    dot: "7444298",
    equipment: "Dry van",
    trucks: 3,
    status: "ACTIVE",
    score: 76,
  },
  {
    name: "Androscoggin Hauling",
    city: "Auburn",
    dot: "7456621",
    equipment: "Reefer",
    trucks: 5,
    status: "ACTIVE",
    score: 79,
  },
  {
    name: "Biddeford Border Freight",
    city: "Biddeford",
    dot: "7462037",
    equipment: "Power only",
    trucks: 2,
    status: "ACTIVE",
    score: 95,
  },
  {
    name: "Downeast Seafood Carriers",
    city: "Portland",
    dot: "7478359",
    equipment: "Reefer",
    trucks: 7,
    status: "WARNING",
    score: 61,
  },
  {
    name: "Nezhinsky Cargo Lines",
    city: "Bangor",
    dot: "7489912",
    equipment: "Flatbed",
    trucks: 1,
    status: "INACTIVE",
    score: 38,
  },
];
