import type { StateCarrierRow } from "@/components/StateCarriersPage";

export const NEW_MEXICO_CARRIERS: StateCarrierRow[] = [
  {
    name: "Sandia Peak Trucking LLC",
    city: "Albuquerque",
    dot: "8523671",
    equipment: "Dry van",
    trucks: 7,
    status: "ACTIVE",
    score: 91,
  },
  {
    name: "High Desert Carriers Inc.",
    city: "Santa Fe",
    dot: "8567395",
    equipment: "Reefer",
    trucks: 2,
    status: "ACTIVE",
    score: 94,
  },
  {
    name: "Rio Grande Freight Co.",
    city: "Las Cruces",
    dot: "8512340",
    equipment: "Flatbed",
    trucks: 5,
    status: "ACTIVE",
    score: 88,
  },
  {
    name: "Zia Line Logistics",
    city: "Rio Rancho",
    dot: "8534982",
    equipment: "Dry van",
    trucks: 4,
    status: "ACTIVE",
    score: 82,
  },
  {
    name: "Roswell Flatbed & Freight",
    city: "Roswell",
    dot: "8556804",
    equipment: "Flatbed",
    trucks: 6,
    status: "ACTIVE",
    score: 79,
  },
  {
    name: "Volga Line Transport",
    city: "Albuquerque",
    dot: "8545213",
    equipment: "Power only",
    trucks: 3,
    status: "ACTIVE",
    score: 76,
  },
  {
    name: "Four Corners Trucking",
    city: "Farmington",
    dot: "8578126",
    equipment: "Dry van",
    trucks: 8,
    status: "WARNING",
    score: 61,
  },
  {
    name: "Border Route Transport LLC",
    city: "Las Cruces",
    dot: "8589457",
    equipment: "Flatbed",
    trucks: 1,
    status: "INACTIVE",
    score: 38,
  },
];
