export type StateDirectoryEntry = {
  name: string;
  slug: string;
  count: string;
};

// Kept alphabetical; count mirrors each state page's own STATS/totalCount.
export const STATE_DIRECTORY: StateDirectoryEntry[] = [
  { name: "Alabama", slug: "alabama", count: "16,500" },
  { name: "Alaska", slug: "alaska", count: "2,100" },
  { name: "Arizona", slug: "arizona", count: "24,700" },
  { name: "Arkansas", slug: "arkansas", count: "15,200" },
  { name: "California", slug: "california", count: "71,400" },
  { name: "Colorado", slug: "colorado", count: "23,900" },
  { name: "Connecticut", slug: "connecticut", count: "11,800" },
  { name: "Delaware", slug: "delaware", count: "4,900" },
  { name: "Florida", slug: "florida", count: "38,900" },
  { name: "Georgia", slug: "georgia", count: "29,800" },
  { name: "Hawaii", slug: "hawaii", count: "2,600" },
  { name: "Idaho", slug: "idaho", count: "8,700" },
  { name: "Illinois", slug: "illinois", count: "34,600" },
  { name: "Indiana", slug: "indiana", count: "30,200" },
  { name: "Iowa", slug: "iowa", count: "17,400" },
  { name: "Kansas", slug: "kansas", count: "16,600" },
  { name: "Kentucky", slug: "kentucky", count: "19,700" },
  { name: "Louisiana", slug: "louisiana", count: "18,900" },
  { name: "Maine", slug: "maine", count: "7,820" },
  { name: "Maryland", slug: "maryland", count: "17,900" },
  { name: "Massachusetts", slug: "massachusetts", count: "21,300" },
  { name: "Michigan", slug: "michigan", count: "27,600" },
  { name: "Minnesota", slug: "minnesota", count: "22,400" },
  { name: "Mississippi", slug: "mississippi", count: "12,100" },
  { name: "Missouri", slug: "missouri", count: "24,900" },
  { name: "Montana", slug: "montana", count: "9,640" },
  { name: "Nebraska", slug: "nebraska", count: "14,500" },
  { name: "Nevada", slug: "nevada", count: "13,700" },
  { name: "New Hampshire", slug: "new-hampshire", count: "6,900" },
  { name: "New Jersey", slug: "new-jersey", count: "19,300" },
  { name: "New Mexico", slug: "new-mexico", count: "10,300" },
  { name: "New York", slug: "new-york", count: "42,300" },
  { name: "North Carolina", slug: "north-carolina", count: "31,600" },
  { name: "North Dakota", slug: "north-dakota", count: "6,200" },
  { name: "Ohio", slug: "ohio", count: "27,500" },
  { name: "Oklahoma", slug: "oklahoma", count: "19,100" },
  { name: "Oregon", slug: "oregon", count: "16,800" },
  { name: "Pennsylvania", slug: "pennsylvania", count: "26,100" },
  { name: "Rhode Island", slug: "rhode-island", count: "3,400" },
  { name: "South Carolina", slug: "south-carolina", count: "17,200" },
  { name: "South Dakota", slug: "south-dakota", count: "7,100" },
  { name: "Tennessee", slug: "tennessee", count: "28,400" },
  { name: "Texas", slug: "texas", count: "48,210" },
  { name: "Utah", slug: "utah", count: "15,900" },
  { name: "Vermont", slug: "vermont", count: "3,900" },
  { name: "Virginia", slug: "virginia", count: "23,600" },
  { name: "Washington", slug: "washington", count: "25,700" },
  { name: "West Virginia", slug: "west-virginia", count: "8,300" },
  { name: "Wisconsin", slug: "wisconsin", count: "21,900" },
  { name: "Wyoming", slug: "wyoming", count: "4,700" },
];
